package tr.gov.nvi.tckimlik.WS;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.2.0
//
// Created by Quasar Development 
//
//----------------------------------------------------

import java.util.Date;


public interface SHADateTimeConverter {
    Date convertDateTime(String strDate);

    Date convertTime(String strDate);

    Date convertDate(String strDate);

    String convertDuration(String value);

    String getStringFromDateTime(Date value);

    String getStringFromDate(Date value);

    String getStringFromTime(Date value);

    String getStringFromDuration(String value);
}